-- Spare Parts Inventory Management System schema (Supabase / PostgreSQL)
-- Static-frontend edition: the browser talks to Supabase directly using the
-- public "anon" key, so this schema also opens up Row Level Security policies
-- and a Storage bucket for PDF manuals.
--
-- Run this once: Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table if not exists machines (
    id              bigint generated by default as identity primary key,
    name            text not null,
    model           text,
    serial_number   text,
    manufacturer    text,
    year_built      integer,
    notes           text,
    created_at      timestamptz not null default now()
);

create table if not exists parts (
    id              bigint generated by default as identity primary key,
    part_code       text not null unique,
    description     text,
    uom             text default 'Nos',
    stock_qty       integer not null default 0,
    reorder_level   integer not null default 0,
    unit_cost       numeric default 0,
    location        text,
    created_at      timestamptz not null default now()
);

-- Safe to re-run: adds the uom (Unit of Measure) column if you already ran an
-- earlier version of this schema and don't want to drop your existing data.
alter table parts add column if not exists uom text default 'Nos';

create table if not exists assemblies (
    id              bigint generated by default as identity primary key,
    machine_id      bigint not null references machines(id) on delete cascade,
    drawing_code    text,
    name            text,
    created_at      timestamptz not null default now()
);

create table if not exists assembly_parts (
    id              bigint generated by default as identity primary key,
    assembly_id     bigint not null references assemblies(id) on delete cascade,
    part_id         bigint not null references parts(id) on delete cascade,
    position        text,
    quantity        integer not null default 1
);

-- storage_path is the object key inside the "manuals" Storage bucket, which
-- may differ from the original filename (we timestamp it to avoid collisions).
create table if not exists manuals (
    id              bigint generated by default as identity primary key,
    machine_id      bigint not null references machines(id) on delete cascade,
    filename        text not null,
    storage_path    text not null,
    volume_label    text,
    uploaded_at     timestamptz not null default now()
);

create table if not exists breakdowns (
    id              bigint generated by default as identity primary key,
    machine_id      bigint not null references machines(id) on delete cascade,
    part_id         bigint references parts(id) on delete set null,
    description     text not null,
    reported_by     text,
    qty_used        integer default 0,
    reported_at     timestamptz not null default now(),
    resolved_at     timestamptz,
    resolution      text
);

create table if not exists stock_check_uploads (
    id              bigint generated by default as identity primary key,
    filename        text,
    row_count       integer,
    matched_count   integer,
    unmatched_count integer,
    uploaded_at     timestamptz not null default now()
);

create index if not exists idx_parts_code on parts(part_code);
create index if not exists idx_breakdowns_machine on breakdowns(machine_id);
create index if not exists idx_breakdowns_part on breakdowns(part_id);
create index if not exists idx_assembly_parts_assembly on assembly_parts(assembly_id);
create index if not exists idx_assembly_parts_part on assembly_parts(part_id);
create index if not exists idx_manuals_machine on manuals(machine_id);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
-- IMPORTANT: This app has no login system, and the browser talks to Supabase
-- directly using the public "anon" key (visible to anyone who opens dev tools
-- on your site). The policies below grant that anon key full read/write
-- access to every table, matching the original app's "no login required"
-- behavior. This means anyone with your Supabase URL + anon key can read and
-- write this data directly, not only through your app's UI.
--
-- If that's a concern, the next step up is enabling Supabase Auth and
-- rewriting these policies to check auth.uid() instead of "using (true)".

alter table machines enable row level security;
alter table parts enable row level security;
alter table assemblies enable row level security;
alter table assembly_parts enable row level security;
alter table manuals enable row level security;
alter table breakdowns enable row level security;
alter table stock_check_uploads enable row level security;

create policy "public access" on machines for all using (true) with check (true);
create policy "public access" on parts for all using (true) with check (true);
create policy "public access" on assemblies for all using (true) with check (true);
create policy "public access" on assembly_parts for all using (true) with check (true);
create policy "public access" on manuals for all using (true) with check (true);
create policy "public access" on breakdowns for all using (true) with check (true);
create policy "public access" on stock_check_uploads for all using (true) with check (true);

-- ---------------------------------------------------------------------------
-- Storage bucket for PDF manuals
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('manuals', 'manuals', true)
on conflict (id) do nothing;

create policy "public read manuals bucket"
on storage.objects for select
using (bucket_id = 'manuals');

create policy "public upload manuals bucket"
on storage.objects for insert
with check (bucket_id = 'manuals');

create policy "public delete manuals bucket"
on storage.objects for delete
using (bucket_id = 'manuals');
