-- Spare Parts Inventory Management System schema (Supabase / PostgreSQL)
-- Static-frontend edition: the browser talks to Supabase directly using the
-- public "anon" key, so this schema also opens up Row Level Security policies
-- and a Storage bucket for PDF manuals.
--
-- Run this once: Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table if not exists machines (
    id              bigint generated by default as identity primary key,
    name            text not null,
    model           text,
    serial_number   text,
    manufacturer    text,
    year_built      integer,
    notes           text,
    created_at      timestamptz not null default now()
);

create table if not exists parts (
    id              bigint generated by default as identity primary key,
    part_code       text not null unique,
    description     text,
    uom             text default 'Nos',
    stock_qty       integer not null default 0,
    reorder_level   integer not null default 0,
    unit_cost       numeric default 0,
    location        text,
    created_at      timestamptz not null default now()
);

-- Safe to re-run: adds the uom (Unit of Measure) column if you already ran an
-- earlier version of this schema and don't want to drop your existing data.
alter table parts add column if not exists uom text default 'Nos';

create table if not exists assemblies (
    id              bigint generated by default as identity primary key,
    machine_id      bigint not null references machines(id) on delete cascade,
    drawing_code    text,
    name            text,
    created_at      timestamptz not null default now()
);

create table if not exists assembly_parts (
    id              bigint generated by default as identity primary key,
    assembly_id     bigint not null references assemblies(id) on delete cascade,
    part_id         bigint not null references parts(id) on delete cascade,
    position        text,
    quantity        integer not null default 1
);

-- storage_path is the object key inside the "manuals" Storage bucket, which
-- may differ from the original filename (we timestamp it to avoid collisions).
create table if not exists manuals (
    id              bigint generated by default as identity primary key,
    machine_id      bigint not null references machines(id) on delete cascade,
    filename        text not null,
    storage_path    text not null,
    volume_label    text,
    uploaded_at     timestamptz not null default now()
);

create table if not exists breakdowns (
    id              bigint generated by default as identity primary key,
    machine_id      bigint not null references machines(id) on delete cascade,
    part_id         bigint references parts(id) on delete set null,
    description     text not null,
    reported_by     text,
    qty_used        integer default 0,
    reported_at     timestamptz not null default now(),
    resolved_at     timestamptz,
    resolution      text
);

create table if not exists stock_check_uploads (
    id              bigint generated by default as identity primary key,
    filename        text,
    row_count       integer,
    matched_count   integer,
    unmatched_count integer,
    uploaded_at     timestamptz not null default now()
);

create index if not exists idx_parts_code on parts(part_code);
create index if not exists idx_breakdowns_machine on breakdowns(machine_id);
create index if not exists idx_breakdowns_part on breakdowns(part_id);
create index if not exists idx_assembly_parts_assembly on assembly_parts(assembly_id);
create index if not exists idx_assembly_parts_part on assembly_parts(part_id);
create index if not exists idx_manuals_machine on manuals(machine_id);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
-- IMPORTANT: This app has no login system, and the browser talks to Supabase
-- directly using the public "anon" key (visible to anyone who opens dev tools
-- on your site). The policies below grant that anon key full read/write
-- access to every table, matching the original app's "no login required"
-- behavior. This means anyone with your Supabase URL + anon key can read and
-- write this data directly, not only through your app's UI.
--
-- If that's a concern, the next step up is enabling Supabase Auth and
-- rewriting these policies to check auth.uid() instead of "using (true)".

alter table machines enable row level security;
alter table parts enable row level security;
alter table assemblies enable row level security;
alter table assembly_parts enable row level security;
alter table manuals enable row level security;
alter table breakdowns enable row level security;
alter table stock_check_uploads enable row level security;

-- ---------------------------------------------------------------------------
-- Authentication: profiles, roles, and login tracking
-- ---------------------------------------------------------------------------
-- Supabase Auth manages the real auth.users table (email/password, sessions).
-- This "profiles" table is where the app tracks its own data about each
-- user: their role (admin/user) and whether an admin has approved them.
-- Self-signup is allowed (no backend/service-role key needed for that), but
-- a brand-new account has approved=false and role='user' by default, and
-- every policy below blocks ALL data access until an admin approves it —
-- so signing up costs nothing but doesn't grant anything either.

create table if not exists profiles (
    id          uuid primary key references auth.users(id) on delete cascade,
    email       text not null,
    full_name   text,
    role        text not null default 'user' check (role in ('admin', 'user')),
    approved    boolean not null default false,
    created_at  timestamptz not null default now()
);

-- Auto-create a profile row whenever someone signs up.
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, email)
    values (new.id, new.email)
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure handle_new_user();

-- Helper functions used by RLS policies below. SECURITY DEFINER lets them
-- read `profiles` without recursing back through profiles' own RLS policy.
create or replace function is_approved()
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (
        select 1 from profiles where id = auth.uid() and approved = true
    );
$$;

create or replace function is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (
        select 1 from profiles where id = auth.uid() and approved = true and role = 'admin'
    );
$$;

-- One row per successful sign-in, written by the app right after login —
-- this is your "who has logged in" history.
create table if not exists login_log (
    id             bigint generated by default as identity primary key,
    user_id        uuid references auth.users(id) on delete set null,
    email          text,
    logged_in_at   timestamptz not null default now()
);

alter table profiles enable row level security;
alter table login_log enable row level security;

create policy "view own profile" on profiles for select using (auth.uid() = id);
create policy "admins view all profiles" on profiles for select using (is_admin());
create policy "admins update profiles" on profiles for update using (is_admin()) with check (is_admin());

create policy "log own logins" on login_log for insert with check (auth.uid() = user_id);
create policy "admins view login log" on login_log for select using (is_admin());

-- IMPORTANT — bootstrapping your first admin:
-- Every new signup starts as role='user', approved=false, and nobody can
-- approve anyone until at least one admin exists. After you sign up for the
-- very first time, run this once in the SQL Editor (with your real email):
--
--   update profiles set role = 'admin', approved = true where email = 'you@yourcompany.com';
--
-- After that, use the Users tab in the app for everyone else.

-- ---------------------------------------------------------------------------
-- Row Level Security — now gated on an approved account, not fully public.
-- DELETE on parts and machines is admin-only, since those are the hardest
-- actions to undo (Delete All Parts, deleting a machine and its assemblies).
-- ---------------------------------------------------------------------------
drop policy if exists "public access" on machines;
drop policy if exists "public access" on parts;
drop policy if exists "public access" on assemblies;
drop policy if exists "public access" on assembly_parts;
drop policy if exists "public access" on manuals;
drop policy if exists "public access" on breakdowns;
drop policy if exists "public access" on stock_check_uploads;

create policy "approved read" on machines for select using (is_approved());
create policy "approved write" on machines for insert with check (is_approved());
create policy "approved update" on machines for update using (is_approved()) with check (is_approved());
create policy "admin delete" on machines for delete using (is_admin());

create policy "approved read" on parts for select using (is_approved());
create policy "approved write" on parts for insert with check (is_approved());
create policy "approved update" on parts for update using (is_approved()) with check (is_approved());
create policy "admin delete" on parts for delete using (is_admin());

create policy "approved access" on assemblies for all using (is_approved()) with check (is_approved());
create policy "approved access" on assembly_parts for all using (is_approved()) with check (is_approved());
create policy "approved access" on manuals for all using (is_approved()) with check (is_approved());
create policy "approved access" on breakdowns for all using (is_approved()) with check (is_approved());
create policy "approved access" on stock_check_uploads for all using (is_approved()) with check (is_approved());

-- ---------------------------------------------------------------------------
-- Storage bucket for PDF manuals
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('manuals', 'manuals', true)
on conflict (id) do nothing;

drop policy if exists "public read manuals bucket" on storage.objects;
drop policy if exists "public upload manuals bucket" on storage.objects;
drop policy if exists "public delete manuals bucket" on storage.objects;

create policy "approved read manuals bucket"
on storage.objects for select
using (bucket_id = 'manuals' and is_approved());

create policy "approved upload manuals bucket"
on storage.objects for insert
with check (bucket_id = 'manuals' and is_approved());

create policy "approved delete manuals bucket"
on storage.objects for delete
using (bucket_id = 'manuals' and is_approved());
